### ISSUE TITLE
Feature: changelog based on PRs / branches? 

### ISSUE THREAD

**Issue by anrico-oltmanns** [mikepenz/release-changelog-builder-action#1011]
Hey,

I wanted to use your changelog action because it seems to be the best in the marked based on the configurations you can easily make. I wanted to use this tool in a github action for our weekly master merge. So our workflow is:

- we create a new branch for every issue/PR. (we dont! use tags or changelogs at all)
- we merge this new branch to `develop`.
- every week we merge everything from `develop` to `master` (this PR might include 10-20 PRs).

So now I was looking for a tool that I can include in our github action that automatically creates that weekly PR. I want to have a tool which list all the PRs we merged to develop and then save it as an output. Then I want to use this output for the body (the desciption) of the PR. I tried configuring your action and implementing it in our workflow. It seems to be all based on tags. We dont really want to use tags. 

Anything I missed? Might it be possible for my use-case? Thinking about configuring it that way? Any help would be great!

**Comment by mikepenz** [comment]
Thank you for the ticket. 

The `toTag` and `fromTag` also allow to be configured with a valid `git ref`. 

<img width="828" alt="Screenshot 2023-01-25 at 15 05 51" src="https://user-images.githubusercontent.com/1476232/214584421-ebc05d67-855f-41ed-a502-9d72ea1ad5c8.png">

**Comment by mikepenz** [comment]
Putting this into action - could make the config as simple as:

```
name: Release
on:
  push:
    branches: [ main ]
    
...

      - name: Release Changelog Builder
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          fromTag: ${{github.event.before}}
          toTag: ${{github.event.after}}
```

---

E.g. every week when you merge into `main` - there is the `push` event - which will then trigger the changelog between the last state of `main` to the new state.
