### ISSUE TITLE
Question: Categorize By Branch Prefix?

### ISSUE THREAD

**Issue by kvernon** [mikepenz/release-changelog-builder-action#1028]
Recently I've been tasked w/ categorizing by branch prefix. (feature/, bugfix/, chore/, etc...), and going through the config, I'm trying to find ways to tap into it. **I'm hoping for some advice on using your amazing config.**

1. _The easiest way,_ is there a way to create a changelog that has `uncategorized_prs` (actual, not the count)?
2. If teams add into the PR title: "feature: Add Super Widget," could I extract the first part, "feature" and have that as the category?

Thanks,
Kelly

**Comment by mikepenz** [comment]
Good day @kvernon 

There are quite a few option you have in this regards. 

1.) Uncategorized PRs can be placed in a changelog by using the following placeholder `${{UNCATEGORIZED}}` in the template
2.) You can use the `label_extractor` to extract additional labels from PRs. This would allow you to use a regex to get a label from a PR title, but also from it's branch (possible properties to get values from: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L34-L43) 

There are some examples in the test cases: https://github.com/mikepenz/release-changelog-builder-action/blob/dffddcd83353ebb1c64f53b6cacfd6e24b707728/__tests__/transform.test.ts#L145
https://github.com/mikepenz/release-changelog-builder-action/blob/dffddcd83353ebb1c64f53b6cacfd6e24b707728/configs_test/configuration_base_branches_main.json#L14

**Comment by kvernon** [comment]
Thanks again @mikepenz !

This has given me a lot to think about, and I really appreciate seeing unit tests 👍 

I think this is where I'm wrapped up, and hopefully you can shed some light on it.

1. template vs pr_template (and their order).

```text
  "template": "${{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n${{UNCATEGORIZED}}\n</details>",
  "pr_template": "- ${{TITLE}}\\n   - PR: #${{NUMBER}}",
```

My wild stab..
template: used to write the changelog... the above states that I'm taking in the current changelog and then appending to the data `details...(through)...summary`

pr_template: used to extract the title of the PR or possibly a Raw PR (title, body, and number are all mixed together)

2. After some mixing of configs (ideas from this repo), I get uncategorized entries 🍾  Unfortunately, I'm getting an issue:

```bash
Error: Unable to process file command 'env' successfully.
Error: Invalid format '<details>'
```

3. is there a way to see what labels it creates? (a debug option type thing?) I'm currently validating regex, but when it's entered, I'm not quite getting the same results.

**Comment by mikepenz** [comment]
@kvernon trying to parse through the above. It looks you discovered most of the answers already. 

Just in case:

`template` - The overall template for the whole generated release notes. Whereas some placeholders will be filled with the respective items (e.g. CHANGELOG contains all categorized PR entries, whereas UNCATEGORIZED all non categorized ones) 
`pr_template` - The template used for an individual PR. Which can then host placeholders being filled with PR specific elements. 


The error looks like the provided config is failing within `github actions` already possibly. Can you share how you define things?


Yes that's a good approach to retrieve the labels, but having more debug logs is certainly a good idea. Will look into it

**Comment by mikepenz** [comment]
Before I totally forget a complete alternative is, to use `Regex` based rules to match PRs for a category
<img width="811" alt="Screenshot 2023-02-26 at 11 46 26" src="https://user-images.githubusercontent.com/1476232/221405880-4bfe98e9-7b65-4722-a6e3-bc17dddbff3c.png">

**Comment by kvernon** [comment]
Thanks again Mike!

I wound up having a hard quit due to a forced company install of updates. I did wind up doing the following (in addition to using the new 3.7.0 update you provided):

config:
```json
{
  "max_tags_to_fetch": 200,
  "max_pull_requests": 200,
  "max_back_track_time_days": 365,
  "empty_template": "- no changes",
  "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}",
  "categories": [
    {
      "title": "## 🚀 Features",
      "labels": [
        "feature",
        "feat"
      ]
    },
    {
      "title": "## 🐛 Fixes",
      "labels": [
        "fix",
        "bugfix",
        "hotfix"
      ]
    },
    {
      "title": "## 🧪 Tests",
      "labels": [
        "test"
      ]
    },
    {
      "title": "## ???? Unknown",
      "labels": [
        "unknown"
      ]
    }
  ],
  "ignore_labels": [
    "ignore",
    "release"
  ],
  "label_extractor": [
    {
      "pattern": "(^\\w+)",
      "method": "match",
      "on_property": "branch",
      "flags": "giu",
      "on_empty": "unknown"
    }
  ]
}

```

I do get a changelog of sorts, so that's good... and thank you!

```yml
#...
inputs:
  config:
    description: 'used to setup writing the changelog. See https://github.com/marketplace/actions/release-changelog-builder#configuration for more info on this.'
    required: false
    default: '.github/changelog.json'
    type: string
  outputFile:
    description: 'used to say where it is saving the file to. The default is ./CHANGELOG.md'
    required: false
    default: './CHANGELOG.md'
    type: string

#...

    - name: Build Changelog Both Versions
      id: changelogWithBothVersionInputs
      if: ${{ inputs.toTag != '' && inputs.fromTag != '' }}
      continue-on-error: true
      uses: mikepenz/release-changelog-builder-action@v3.7.0
      with:
        configuration: "${{ inputs.config }}"
        fromTag: "${{ inputs.fromTag }}"
        toTag: "${{ inputs.toTag }}"
        outputFile: "${{ inputs.outputFile }}"
        ignorePreReleases: "${{ inputs.ignorePreReleases }}"
        includeOpen: false
        failOnError: ${{ inputs.failOnError }}
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}

    - name: Update Changelog With Proposed Input
      if: ${{ inputs.toTag != '' && inputs.fromTag == '' }}
      shell: bash
      run: |
        echo  "changelog=${{ steps.changelogWithToTagVersionInput.outputs.changelog }}" >> $GITHUB_ENV
```

One thing I'm find odd is that this tool, doesn't seem to like sharing github_env because in isolation of another step I get this error:

```bash
Error: Unable to process file command 'env' successfully.
Error: Invalid format '- feat: adding build number'
```

I don't understand why this doesn't want me to write to an environment. Is there some restriction in place?

What my goal is that I'm hoping for here is that, we append to a changelog and get the current changelog, so we can include  it into the release notes.

**Comment by mikepenz** [comment]
Currently a bit busy. So I can't look into the whole config. But I know what is causing the 
```
Error: Unable to process file command 'env' successfully.
Error: Invalid format '- feat: adding build number'
```
output. 

So you set the `GITHUB_ENV` via a normal `bash` shell. But the way you do this is by doing an `echo`. As soon as there is any character in the `changelog` which breaks the string. So maybe you have a `"` somewhere or such. It won't be escaped. 

The best way to fix this. (And I highly recommend that for all variables you us in bash, so they are properly escaped and as such more secure). Theoretically with the above, somebody could inject code into your bash by exploiting that given line. 

To prevent that, and to fix the issue do the following instead:

```
    - name: Update Changelog With Proposed Input
      if: ${{ inputs.toTag != '' && inputs.fromTag == '' }}
      shell: bash
      run: |
        echo  "changelog=${CHANGELOG}" >> $GITHUB_ENV
      env:
        CHANGELOG: ${{ steps.changelogWithToTagVersionInput.outputs.changelog }}
```
