### ISSUE TITLE
`commitMode: true` does not seem to work

### ISSUE THREAD

**Issue by xiaoyifang** [mikepenz/release-changelog-builder-action#1136]
use default configuration.

```
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: true
```
