### ISSUE TITLE
Usage Issue with Internal Organization

### ISSUE THREAD

**Issue by sethicis** [mikepenz/release-changelog-builder-action#1156]
## Situation

I'm attempting to use this action for a workflow I'm setting up with my company.  The problem I keep running into is that the action reports for the `Resolved Tags` "Not Found".

The repository action I'm attempting to build a change log for is a separate internal repo, not the one this action is running on.  I am using a PAT that has access to both repositories.  We do not use releases in this GitHub repository, but we do tag all of our versions before pushing them to our private NPM registry.  Each tag looks like `v2.1.3`.

I can't give the exact same implementation I have for privacy reasons, but I'll put an example that's similar to my usage of this action below.

```
steps:
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          owner: org-name
          repo: org-name/node-app
          fromTag: v${{ env.OLD_VERSION }}
          toTag: v${{ env.NEW_VERSION }}
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
```

I'm kind of stumped.  I don't know why the action keeps failing to find any of the resolved tags.  Please let me know if you require any additional information.
