### ISSUE TITLE
use v4 gitea generate changelog fail

### ISSUE THREAD

**Issue by hb0730** [mikepenz/release-changelog-builder-action#1297]
* use v4.0.1
![image](https://github.com/mikepenz/release-changelog-builder-action/assets/33956166/db241463-a094-4c5c-81ee-9b43bed376d3)
* use v4
![image](https://github.com/mikepenz/release-changelog-builder-action/assets/33956166/cb1f3360-22e0-4a97-a6a9-88097f7bcbd1)

```yaml
- name: Generate Changelog
  id: changelog
  uses: https://github.com/mikepenz/release-changelog-builder-action@v4
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    platform: "gitea"
    baseUrl: "http://gitea:3000"
    commitMode: true
    configuration: "configuration.json"
```

**`https://github.com/dreamncn/release-changelog-builder-action@v4.0.1`** this is available
