### ISSUE TITLE
How to use this - set labels/use commits messages

### ISSUE THREAD

**Issue by mStirner** [mikepenz/release-changelog-builder-action#1303]
I want to use this in my automatic release workflow to generate a changelog.
But no matter what i do i see always "no changes" in my playground release.

How/what do i have to put in my git commits to appear in the release changelog?

Playground repo: https://github.com/mStirner/playground-test-auto-release
Workflow:
```yml
name: Release Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run release

      - name: "Read package.json"
        run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create GitHub release"    
        uses: ncipollo/release-action@v1        
        with:
          artifacts: "dist/*"
          tag: "v${{ fromJson(env.PACKAGE_JSON).version }}"
          generateReleaseNotes: false
          skipIfReleaseExists: true
          body: ${{steps.build_changelog.outputs.changelog}}
```

No matter what, and how i format it in the git commit message, im unable to see it in the release output. Does not work:
- \[fix\]: foo
- \`fix\`: foo
- fix: foo

How should "labels" be define to be recognized by this action?
I did not found anything about that in the documentation/readme.

In the action output (https://github.com/mStirner/playground-test-auto-release/actions/runs/7929554235/job/21650025772#step:7:36) it prints: "No pull requests found"

**Comment by mikepenz** [comment]
The action by default works with pull requests only. It appears you are trying to use it without pull requests but instead with commits?

<img width="920" alt="Screenshot 2024-02-16 at 14 16 08" src="https://github.com/mikepenz/release-changelog-builder-action/assets/1476232/5ef7bb1a-29ef-4f5e-96e5-11aa4f75d47e">

Please configure the action to run in the `commit` based mode. However remember that commits have less information than pull requests, so you will need to provide additional configuration to tell the action how to categorize your commits. 

There are some test cases around that which can probably give you some pointers on how to configure it: 
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/__tests__/releaseNotesBuilder.test.ts#L257-L286

**Comment by mStirner** [comment]
Thanks for the hint, dont know how i over read that. 
But i encountered a other problem while setting `commitMode` to `true`:

![grafik](https://github.com/mikepenz/release-changelog-builder-action/assets/5003424/9798e723-2e22-4e81-aa92-3521bbefefe9)

The fromatted output looks a bit strange, and for every commit message "PR: #0" is shown: https://github.com/mStirner/playground-test-auto-release/releases/tag/v1.1.6

Also should, a commit message with "fix" or "\`fix\`" not be under the "Fix" Category instead of "Uncategorized"?

**Comment by skaramicke** [comment]
@mStirner I found myself in the same situation and this worked nicely for me:

```yaml
      - name: "Build Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4.1.1
        with:
          commitMode: true
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## What's Changed since #{{FROM_TAG}}",
                  "labels": []
                }
              ],
              "template": "#{{CHANGELOG}}",
              "pr_template": "- #{{TITLE}}\n",
              "empty_template": "#{{OWNER}}\n#{{REPO}}\n#{{FROM_TAG}}\n#{{TO_TAG}}",
              "max_pull_requests": 1000,
              "max_back_track_time_days": 1000
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The key solution to the problem is `pr_template`,  
where the default is something like `"pr_template": "- #{{TITLE}}\n   - PR: ##{{NUMBER}}"`

Here's a screenshot of my result:

![image](https://github.com/mikepenz/release-changelog-builder-action/assets/536960/34d2fc6e-8c79-4b6a-bdfb-94f0c7727823)

@mikepenz Thanks for your work! It's a great tool in my workflow.

**Comment by mikepenz** [comment]
Thank you so much @skaramicke for the kind work and chiming in on this issue providing help :) 

@mStirner please have a look on the information related the template per PR (or in your case commit)

to the second question regarding categorisation. 

As noted in my first message, the action by default uses pull requests (and on these labels) to categorize the information, however none of this exists for commit messages. For commit messages you will be required to provide your own logic to extract the categories. 

Please see the example I referenced before, it uses the label_extractor and transformers to get the "labels" you want for your case to cateogrize (this example is based on the test which uses emojis, but is transformable to any other pattern you anyone may use - https://github.com/mikepenz/release-changelog-builder-action/blob/develop/configs_test/configuration_commits_emoji.json#L24-L36)

**Comment by mStirner** [comment]
Thank you very much @skaramicke. Your reply helped me a lot.
But there is one thing that i find "confusing". 

My latest release is `v1.1.9`, the previous one is `v1.1.8`.
But in the changelog is written "What's Changed since v1.1.7".
Why does it skip `v1.1.8`?

Same for release `v1.1.8`, it says in release notes "What's Changed since v1.1.6".
Why does it skip the release `v1.1.7`?

![grafik](https://github.com/mikepenz/release-changelog-builder-action/assets/5003424/88628d52-0602-4b58-8feb-bbc73730a6fd)

https://github.com/mStirner/playground-test-auto-release/releases

**Comment by skaramicke** [comment]
That seems weird. Are you using #{{FROM_TAG}}?

Mine seems perfectly sequential

![image](https://github.com/mikepenz/release-changelog-builder-action/assets/536960/315da171-c91d-47b3-9676-1feb433d88b5)

**Comment by mStirner** [comment]
I copy & pasted your json config.
Thats the current workflow file:

```yml
name: Release Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run release

      - name: "Read package.json"
        run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          commitMode: true
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## What's Changed since #{{FROM_TAG}}",
                  "labels": []
                }
              ],
              "template": "#{{CHANGELOG}}",
              "pr_template": "- #{{TITLE}}\n",
              "empty_template": "#{{OWNER}}\n#{{REPO}}\n#{{FROM_TAG}}\n#{{TO_TAG}}",
              "max_pull_requests": 1000,
              "max_back_track_time_days": 1000
            }          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create GitHub release"    
        uses: ncipollo/release-action@v1        
        with:
          artifacts: "dist/*"
          tag: "v${{ fromJson(env.PACKAGE_JSON).version }}"
          generateReleaseNotes: false
          skipIfReleaseExists: true
          body: ${{steps.build_changelog.outputs.changelog}}
```

Yes, i use `#{{FROM_TAG}}`
