### ISSUE TITLE
TO_TAG_DATE blank, and question about passing data

### ISSUE THREAD

**Issue by Aetherinox** [mikepenz/release-changelog-builder-action#1317]
I noticed that `TO_TAG_DATE` never returns anything and is blank.

I have it utilized as:

```
"## What's New\n<sup>Version began on: #{{FROM_TAG_DATE}} - #{{TO_TAG_DATE}}</sup>\n<br />
```

and I've ensured I satisfied the requirements per the readme:

```yml
- name: Build Changelog
  id: changelog
  uses: mikepenz/release-changelog-builder-action@v4
  with:
    fromTag: "${{ env.TAG_LAST }}"
    toTag: ${{ github.ref }}
    configuration: ".github/changelog-configuration.json"
    ignorePreReleases: false
    commitMode: ${{ inputs.CHANGELOG_MODE_COMMIT }}
    fetchReleaseInformation: true
```

Which has `fetchReleaseInformation` enabled. `FROM_TAG_DATE` returns fine, but `TO_TAG_DATE` is blank. Unless I'm missing something else I'm not seeing in the docs.

Second question is in regards to the possibility of passing a value.

Right now I have assigned the configuration file as a `json`. 

I have input values at the top of my action

```yml
on:
  workflow_dispatch:
    inputs:
        BUILD_ID:
        description:  "Build ID"
        required:     true
        type:         string
        default:      00000000-abcd-0123-abcd-000000000000
```

Was wondering if there's a way to pass `${{ BUILD_ID }}` from the action script over to the json as a placeholder. Haven't seen anything in the docs specifically for this. Just the ability to use regex to extract info.

The only other way I can think of to solve this, would be to actually hardcore my json template in the action, which gets a bit sloppy.
