### ISSUE TITLE
Question: Ability to format markdown inside configurationJson

### ISSUE THREAD

**Issue by Aetherinox** [mikepenz/release-changelog-builder-action#1320]
I was poking around, and I even searched for other Github repos using your script and I couldn't seem to find an example, so I thought I'd ask here.

From our last discussion on being able to use variables in a template; you recommended I just throw `template` inside `configurationJson` within my github action yml.

The question: Is their any possibility for me to be able to format this code? Adding line breaks within the template code but it still being rendered in its normal way? I'm just looking for a way to present it in a nicer fashion within my yml file. Because currently, all of the template code is on a single line, and I've had a lot of heavy modifications to the template, and it's making it a royal pain to move the changes between the two different yml files I use this github action on, since they're both not identical and I can't just copy/paste.

My template is as follows:

```yml
configurationJson: |
  {
    "template": "## Release Info \n- <sub>**Version began on**: <sub>........</sub>`#{{FROM_TAG_DATE}}`</sub>\n- <sub>**SHA256**: <sub>................................</sub>`${{ env.SHA256SUM }} 🔺 ${{ env.FILE_ZIP }}`</sub>\n- <sub>**GUID**: <sub>.......................................</sub>`${{ steps.dotenv.outputs.GUID }}`</sub>\n- <sub>**UUID**: <sub>.......................................</sub>`${{ steps.dotenv.outputs.UUID }}</sub>`\n- <sub>**Stamp**: <sub>....................................</sub>`#{{FROM_TAG}}-#{{FROM_TAG_DATE}} 🔺 #{{TO_TAG}}-#{{TO_TAG_DATE}}`</sub>\n- <sub>**Last Release**: <sub>......................</sub>`#{{DAYS_SINCE}} days ago`\n</sup>\n\n<br>\n\n---\n\n<br>\n\n### What's New\nThis release contains the following changes:\n\n<br>\n\n---\n\n<br>\n\n### Statistics\nHow the files have changed:\n<ul><li><a href='#{{RELEASE_DIFF}}'>Changed files</a>  : <b>#{{CHANGED_FILES}}</b> </li><li>Commits : <b>#{{COMMITS}}</b> </li><li>Additions : <b>#{{ADDITIONS}}</b></li><li>Deletions : <b>#{{DELETIONS}}</b></li>\n<br />\n</ul>\n\n<br>\n\n---\n\n<br>\n\n### Commits (#{{UNCATEGORIZED_COUNT}})\n#{{UNCATEGORIZED}}\n\n<br>\n\n---\n\n<br>\n\n### Pull Requests\n#{{CHANGELOG}}\n\n<br>\n\n---\n\n<br>\n\n"
  }
```

There's a lot of `\n` and `<br>` in the template so that I can format it in a nice way. And it's all just jumbled together.

Between Google and Github, I can't seem to find a way to format this, and maybe join the lines together, but it still look the same.
