### ISSUE TITLE
Add a configuration option to write the changelog to file

### ISSUE THREAD

**Issue by ccremer** [mikepenz/release-changelog-builder-action#136]
I'd love to combine Goreleaser's release pipeline with this action.
Although Goreleaser includes its own generator, it creates a changelog based on commits. But PRs can sometimes be a better option to convey a history to the human reader.

So, right now I'd have these steps:
```yaml
    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v1.2.3
      with:
        configuration: ".github/changelog-configuration.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: make release notes
      run: echo "${{steps.build_changelog.outputs.changelog}}" >> .github/release-notes.md
    - name: Publish releases
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release --release-notes .github/release-notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

It would be cool to skip this intermediary step like this:
```yaml
    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v1.2.3
      with:
        configuration: ".github/changelog-configuration.json"
        outputFile: ".github/release-notes.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish releases
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release --release-notes .github/release-notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
WDYT?
