### ISSUE TITLE
tag_resolver filter pattern does not work anymore

### ISSUE THREAD

**Issue by KonradHoeffner** [mikepenz/release-changelog-builder-action#1386]
## Workflow

```yaml
name: Release
on:
  push:
    tags: '[2-9][0-9]\.[0-9][0-9]'
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          configurationJson: |
            {
              "pr_template": "- #{{TITLE}}",
              "template": "#{{UNCATEGORIZED}}",
              "tag_resolver": {
                "method": "sort",
                "filter": {
                  "pattern": "[2-9][0-9]\\.[0-9][0-9]"
                }
              }
            }
      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.changelog.outputs.changelog}}
```

## Debug Output

```
Run mikepenz/release-changelog-builder-action@v5
📘 Reading input values
  ℹ️ Retrieved configuration via 'configurationJson'.
  ℹ️ Running in COMMIT mode.
🔖 Resolve tags
  ℹ️ Found 33 (fetching max: 200) tags from the GitHub API for snikproject/graph
  🔖 Resolved current tag (24.10) from the 'github.context.ref'
  🔖 Resolved previous tag (remove-load-cache-from-file) from the tags git API
🚀 Load data
📦 Build changelog
```

## Tags

```sh
graph$ git ls-remote --tags       
From git@github.com:snikproject/graph
05ac9318f71e03d42c84f43b73d40fafc0dc1e9f	refs/tags/0.1.0
88ee0a3ffac9b3f9808a7318a68d88a86578a960	refs/tags/0.1.0^{}
83bb986247fa2ee13baa0751cec223e5b8c78aa2	refs/tags/0.2.0
46991cd0f159521f32f7bee62557338b8ba9cae5	refs/tags/0.2.0^{}
8cc100015a456518cb77d780f0e03bd2a7d1cfeb	refs/tags/0.3.0
110c881c036acd7af3ebb5c4e684b4794f671c7f	refs/tags/0.3.0^{}
80b9a3b2d39f82f5ceb4bee95db9f595128091e4	refs/tags/0.4.0
e28930bbdff4c0382475c26134f889f8b987df55	refs/tags/0.7.0
e125eab8d3ce234626837de55b97ff10b9a11d44	refs/tags/0.8.0
27b100d86874cf2525aeaa0b681075cf66ff7ab2	refs/tags/0.9.0
849208c284076a62fddb1d8ca84eeaa161eee20c	refs/tags/0.9.1
29567644f0bebbff5347b56d6b692cb4a326e460	refs/tags/1.0.0
b079375b0e5eaac749563ccab92033c942bf5560	refs/tags/1.1.0
f8d17ee7ae3520912ab6b130d772a6be02e5ae01	refs/tags/1.2
ab3ffb5bf55730360a2edba69766455043ddea1a	refs/tags/1.3
737858ba4e1ecbddd6ebb1d03024b08a05975eb5	refs/tags/1.4
2d7984bdfaa536a8034ed185e0c7a87dc4fb8711	refs/tags/1.5
0b57948b1d5bfe3cb928787908debcbc9d2bc00f	refs/tags/1.6
99f574eb0c7f14e71460cbb9326a7a4601e8a86c	refs/tags/1.6^{}
a927fa71aa3f15caeb90aa41f87891228803d91a	refs/tags/2.0
6758389ce2aeee0cf2b60ac6edac325cf00b8751	refs/tags/2.0^{}
0e83c5f9b8f52a00c61a4046d8a67af9f57ddddb	refs/tags/2.1
1e33ced424b3ea3b89e2255f675a54273a0b7e4d	refs/tags/2.2
cda207e27d317826404eabd4e9d08750aba52233	refs/tags/22.05
ea458acc8fb4a70fc8743a3ec0a75e0f399e4111	refs/tags/22.10
ce1f86de43eec061c3e45c54f310059b8abdff40	refs/tags/23.04
79dd8a2c910925e85f9f033f50eeaac4147e1c18	refs/tags/23.07
455ca731ccca35a24632ad91909ee65cd854d459	refs/tags/23.10
b67a14009b0342e2d6fc430c1261b536da7093a4	refs/tags/24.01
837113b1a23a807b2b5a1c1e4c2508774347d461	refs/tags/24.04
480128cc8d5749a15a6133038049f608d0d694e1	refs/tags/24.06
8a4bcb83447b5f0b4a268554beb9cd1ac68bad4e	refs/tags/24.07
a78ff8ad972bae319c1342b951216a97d0f9884c	refs/tags/24.10
79ed54887620c9cc517b68548cfc11c48bcea961	refs/tags/3.0
d339efefc5abb79a291e97d9f1d3abe7071a24ea	refs/tags/delete-lunr
ccf84473186c5fd45953f0816de60ef1c6b10bfb	refs/tags/remove-bif-contains
500f6ec63b5e3fb51d078d9b1c96c9f183bc8ee6	refs/tags/remove-bif-contains^{}
4ce265945d43004acb260278baef33778a571a8c	refs/tags/remove-editing
86e69cc36731235fb38347c8060271515c4e8576	refs/tags/remove-load-cache-from-file
81e86af0ce577e4b03a95e5f687ef439f3a5dd39	refs/tags/remove-load-cache-from-file^{}
```

## The problem

The pattern specifies that only two 2-digit numbers (the first digit of the first one starting with a 2 or more) seperated by a dot) are acceptable.
However the tag "remove-load-cache-from-file" is picked up, which violates the filter.

Source: <https://github.com/snikproject/graph/actions/runs/11478165744/job/31941786441>.

## General observations

Since a few weeks(?) ago, this action does not seem to work anymore as before across several of my repositories, see for example also  <https://github.com/mikepenz/release-changelog-builder-action/issues/1383> (there I was asking for explizit CalVer support but I have a similar problem in another repository now and it seems like filters patterns are broken in general) so I felt a separate issue is appropriate.

However it also varies by repository in which way it breaks. For example, in the other repository, it throws an error when I don't have a checkout in front of the changelog step. However in this case a checkout is not required and it finds all the tags perfectly, it just does not filter them out.
