### ISSUE TITLE
Can't ignore commits that are formatted as `ignore: update CHANGELOG.md`

### ISSUE THREAD

**Issue by olimorris** [mikepenz/release-changelog-builder-action#1423]
I have the following workflow:

```yml
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:

      - name: Checkout 🔔
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.head_ref }}

      - name: Get Tags 🎟️
        id: tags
        run: |
          TAGS=$(git tag -l --sort=-version:refname | head -2)
          LATEST_TAG=$(echo "$TAGS" | head -1 | tail -1)
          LATEST_TAG_NAME=${LATEST_TAG#v}
          PREVIOUS_TAG=$(echo "$TAGS" | head -2 | tail -1)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "LATEST_TAG_NAME=$LATEST_TAG_NAME" >> $GITHUB_ENV
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV

      # https://github.com/mikepenz/release-changelog-builder-action
      - name: Build Changelog 🏗️
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          fromTag: "${{ env.PREVIOUS_TAG }}"
          toTag: ${{ env.LATEST_TAG }}
          mode: "COMMIT"
          configurationJson: |
            {
                "categories": [
                    {
                        "title": "## Features",
                        "labels": [
                            "feature",
                            "feat"
                        ]
                    },
                    {
                        "title": "## Bug Fixes",
                        "labels": [
                            "fix",
                            "bug"
                        ]
                    },
                    {
                        "title": "## Other",
                        "labels": []
                    }
                ],
                "ignore_labels": [
                  "ignore:"
                ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/ncipollo/release-action
      - name: Create Release 🚀
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}

      - name: Update Changelog 📖
        run: |
          echo "## [$LATEST_TAG_NAME](https://github.com/olimorris/codecompanion.nvim/compare/$PREVIOUS_TAG...$LATEST_TAG) (`date +%Y-%m-%d`)" >> CHANGELOG.md.tmp
          echo "${{ steps.build_changelog.outputs.changelog }}" >> CHANGELOG.md.tmp
          echo '-n' >> CHANGELOG.md
          cat CHANGELOG.md >> CHANGELOG.md.tmp
          mv CHANGELOG.md.tmp CHANGELOG.md

      # https://github.com/stefanzweifel/git-auto-commit-action
      - name: Commit Changes 📦
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "ignore: update CHANGELOG.md"
          file_pattern: CHANGELOG.md
```

which is largely working as expected...except that release-changelog-builder-action doesn't seem to ignore commits with `ignore:` at the start. From perusing the README, I would expect these to be excluded.

As an aside, I moved to this workflow after Google's Release Please started doing some funky stuff. And I'm super pleased with how slick and functional it is. Any thoughts to enabling discussions where other users can share their workflows?
