### ISSUE TITLE
Question / Issue: Clearing github history and generating new release

### ISSUE THREAD

**Issue by Aetherinox** [mikepenz/release-changelog-builder-action#1439]
Odd question. I have a repository that can get decently large, and as you update files, that size accumulates as part of the repo history. 

I have a Github workflow that clears the repo history once per month, and sets the repo back to its first commit. The issue with that, is when I attempt to release a new version, this workflow throws the error:

```
📦 Package › Release
💥 Failed to retrieve - Invalid tag? - Because of: HttpError: No common ancestor between 14.22.0 and 14.22.1. - https://docs.github.com/rest/commits/commits#compare-two-commits

Run mikepenz/release-changelog-builder-action@v5
📘 Reading input values
  ℹ️ Retrieved configuration via 'configurationJson'.
  ℹ️ Configuration successfully loaded.
  ℹ️ Retrieved configuration via 'configuration' (via file).
  ℹ️ Running in COMMIT mode.
🔖 Resolve tags
  ℹ️ Found 7 (fetching max: 200) tags from the GitHub API for Aetherinox/csf-firewall
  🔖 Resolved current tag (14.22.1) from the tags git API
  🔖 Resolved previous tag (14.22.0) from the tags git API
  ℹ️ Fetching release information was enabled
  ⚠️ No release information found for 14.22.1, trying to retrieve tag creation time as fallback.
  /usr/bin/git for-each-ref --format="%(creatordate:rfc)" refs/tags/14.22.1
  "Tue, 18 Feb 2025 09:59:05 +0000"
  ℹ️ Resolved tag creation time (Tue, 18 Feb 2025 09:59:05 +0000) from 'git for-each-ref --format="%(creatordate:rfc)" "refs/tags/14.22.1
  ℹ️ Retrieved information about the release associated with 14.22.0 from the GitHub API
🚀 Load data
  🚀 Load commit history (⚠️ Executing experimental commit mode)
  ℹ️ Comparing Aetherinox/csf-firewall - '14.22.0...14.22.1'
  Error: 💥 Failed to retrieve - Invalid tag? - Because of: HttpError: No common ancestor between 14.22.0 and 14.22.1. - https://docs.github.com/rest/commits/commits#compare-two-commits
📦 Build changelog
  Warning: ⚠️ No pull requests found
```

I assume it can't find the previous version, because the history has been wiped.

So the question becomes, what is the best way to go about handling this situation. Because now when a release is made, the body of the release just says:

```
No major changes to address in this release
```

Even though all the previous tags and releases are still available on the repo.

The repo is here: https://github.com/Aetherinox/csf-firewall/releases

The workflow code is:

```yml
            - name: "📝 Changelog › Build (Categorized)"
              id: task_release_changelog_categorized
              if: |
                startsWith( inputs.SHOW_UNCATEGORIZED, false ) ||
                startsWith( env.SHOW_UNCATEGORIZED, false )
              uses: mikepenz/release-changelog-builder-action@v5
              with:
                token: ${{ secrets.ADMINSERV_TOKEN }}
                configuration: ".github/changelog-configuration.json"
                ignorePreReleases: false
                commitMode: ${{ inputs.CHANGELOG_MODE_COMMIT || env.CHANGELOG_MODE_COMMIT }}
                fetchReleaseInformation: true
                fetchViaCommits: true
                configurationJson: |

              env:
                GITHUB_TOKEN: ${{ secrets.ADMINSERV_TOKEN }}
```

It does allow for the release, but in the release message body, it just says that there's no changes to list in that version.

And a side note, I have text in the property `configurationJson`. I just removed it here because it's like 20 lines. Just clutter.

Appreciate any direction.
