### ISSUE TITLE
Tag resolver not working as expected when filtering prefixed semver tags

### ISSUE THREAD

**Issue by Gussy** [mikepenz/release-changelog-builder-action#1441]
The `tag_resolver` isn't working as expected. A similar setup used to work on other repos with the `v4` action but at some point it stopped working.

The config.json looks like this:
```json
    "tag_resolver": {
      "method": "semver",
      "filter": {
        "pattern": "api-(.+)",
        "method": "match",
        "flags": "gu"
      }
    },
```

The workflow looks like this:
```yaml
  release-publish:
    name: Publish Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'api-')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build release notes
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: .github/release-configs/bx-firmware.json

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          name: Foobar
          body: ${{steps.build_changelog.outputs.changelog}}
```

The build output:
```
🔖 Resolve tags
  ℹ️ Retrieved 85 (fetching max: 200) tags from the GitHub API for org/repo
  🔖 Resolved current tag (api-0.2.2) from the 'github.context.ref'
  ℹ️ Only one tag found for the given repository. Usually this is the case for the initial release.
  /usr/bin/git rev-list --max-parents=0 HEAD
  36934b97da5b1d2a6dff0541f5950ef347100519
  🔖 Resolved initial commit (36934b97da5b1d2a6dff0541f5950ef347100519) from 'git rev-list --max-parents=0 HEAD'
  🔖 Resolved previous tag (36934b97da5b1d2a6dff0541f5950ef347100519) from the tags git API
```

For now I'm working around the issue by specifiying `toTag` like below, but it would be nice to understand the issue with the `tag_resolver`.
```yaml
toTag: git tag --list "api-*" --no-column --no-contains ${{ github.ref }} | sort -V | tail -n 1
``

There is [a test](https://github.com/mikepenz/release-changelog-builder-action/blob/9da101a8bca331525934ca72b5b9dba5b3b560c2/__tests__/tags.test.ts#L107) for this exact use-case, so I'm sure there's some simple and obvious wrong with my setup, but I haven't been able to figure that out yet. Any help or clues would be appreciated!
