### ISSUE TITLE
release note is not filled on release

### ISSUE THREAD

**Issue by Ludea** [mikepenz/release-changelog-builder-action#1446]
when creating a release, I call release-changelog-builder-action to write the release note from commit history.

```
      - uses: actions/checkout@v4
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          failOnError: true
          ignorePreReleases: false
          configuration: ".github/release_note_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But release is empty. 

GHA logs:
```

Run mikepenz/release-changelog-builder-action@v5
  with:
    mode: COMMIT
    failOnError: true
    ignorePreReleases: false
    configuration: .github/release_note_config.json
    includeOpen: false
    fetchViaCommits: false
    fetchReviewers: false
    fetchReleaseInformation: false
    fetchReviews: false
    commitMode: false
    token: ***
    exportCache: false
    exportOnly: false
    platform: github
  env:
    GITHUB_TOKEN: ***
📘 Reading input values
  ℹ️ Configuration successfully loaded.
  ℹ️ Retrieved configuration via 'configuration' (via file).
  ℹ️ Running in COMMIT mode.
🔖 Resolve tags
  ℹ️ Retrieved 9 (fetching max: 200) tags from the GitHub API for Ludea/Sparus
  🔖 Resolved current tag (v0.3.2-beta.4) from the 'github.context.ref'
  🔖 Resolved previous tag (v0.3.2-beta.3) from the tags git API
🚀 Load data
  🚀 Load commit history (⚠️ Executing experimental commit mode)
  ℹ️ Comparing Ludea/Sparus - 'v0.3.2-beta.3...v0.3.2-beta.4'
  ℹ️ Found 1 commits from the GitHub API for Ludea/Sparus
  ℹ️ Retrieved 1 commits for Ludea/Sparus
📦 Build changelog
  ℹ️ Sorted all pull requests ascending: {"order":"ASC","on_property":"mergedAt"}
  ℹ️ Using 0 transformers to rewrite content
  ℹ️ Ordered all pull requests into 5 categories
  ✒️ Wrote 59 categorized pull requests down
  ✒️ Wrote 0 non categorized pull requests down
  ✒️ Wrote 0 open pull requests down
  ✒️ Wrote 0 ignored pull requests down
  ℹ️ Filled template
```

It found 1 commit, so I expect to see these commit into release note.
