### ISSUE TITLE
Configuration file not found or parsed wrong

### ISSUE THREAD

**Issue by ueberBrot** [mikepenz/release-changelog-builder-action#147]
I have a the following steps in my `.github/workflows/ci.yml` file:

```yml
name: 'CI'
on:
  push:
    tags:
      - 'v*'
  pull_request:
  
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1.3.0
        with:
          configuration: "configs/configuration.json"        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I provided the following configuration file at `configs/configuration.json`:

```json
{
    "categories": [
        {
            "title": "## Features",
            "labels": [
                "feature"
            ]
        },
        {
            "title": "## Fixes",
            "labels": [
                "fix"
            ]
        },
        {
            "title": "## Other",
            "labels": [
                "other"
            ]
        },
        {
            "title": "## Chores",
            "labels": [
                "chore"
            ]
        },
        {
            "title": "## Documentation",
            "labels": [
                "docs"
            ]
        }
    ]
}
```

I tried a simple configuration first but I wanted to add different `titles` and multiple `labels` but i get the following warning when the gh-action is executed:

![image](https://user-images.githubusercontent.com/32489486/103674748-63e00a00-4f7f-11eb-8db7-1f56ea6ee720.png)

I tagged my PRs with only the labels provided in the configuration. My release notes look like this:

![image](https://user-images.githubusercontent.com/32489486/103675538-59724000-4f80-11eb-84cb-400dc70eb0c3.png)

Did I do something wrong?
