### ISSUE TITLE
Can't access config.json

### ISSUE THREAD

**Issue by LeanderGangso** [mikepenz/release-changelog-builder-action#174]
Hi, I noticed that when the workflow job is running is dosen't checkout my repo...
I tried using `actions/checkout@v2`, but I got an error.

Heres my .myl:
```yml
name: Create Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Generate changelog
        id: Changelog
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          outputFile: 'CHANGELOG.md'
          configuration: '.github/config_release_changelog.json'

      - name: Run check
        run: ls -a

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.Changelog.outputs.changelog }}
          draft: 'true'
          prerelease: 'true'

```
