### ISSUE TITLE
Error: The process '/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by tomijais** [mikepenz/release-changelog-builder-action#199]
So im trying to create my first workflow in order to create a good and automate changelog, but i think im missing in something because i cant stop getting this error.

I want to use as a trigger the push to main, in this case to confirm the merge of the PR, what do u recommend me? This is my error.
![image](https://user-images.githubusercontent.com/29215699/109028118-40dcf700-76a0-11eb-8aec-7d33ab8319a2.png)

And this is the changelog.yml
```
name: changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Changelog Builder
        uses: mikepenz/release-changelog-builder-action@v1.5.0
        with:
          fetch-depth: 0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mikepenz** [comment]
Hi @tomijais 

you will need to checkout the repository within your build, as GitHub actions doesn't do that automatically. 
See an example here: https://github.com/mikepenz/FastAdapter/blob/develop/.github/workflows/ci.yml#L15-L18

The `fetch-depth` comment in the README also references the `checkout` action (so please remove that part from this libraries action) 

You can also see the action being used for example in this build here:
https://github.com/mikepenz/FastAdapter/blob/develop/.github/workflows/ci.yml#L117-L125

**Comment by mikepenz** [comment]
If you do not want to checkout the repo for this job you will be required to provide the `toTag` config, as the action won't be able to automatically detect the tag on the current state of the repo:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L35

**Comment by kaermorchen** [comment]
Hello. I have the same issue.

![Screenshot_2021-03-02 Build software better, together](https://user-images.githubusercontent.com/11972062/109661748-5c05a600-7b7b-11eb-8139-f2147e6a211d.png)

```
name: Changelog

on:
  pull_request:
    types: [closed]

  push:
    tags:
      - 'v*'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by mikepenz** [comment]
@kaermorchen you'll need to checkout the repo. Please see my comments above:
https://github.com/mikepenz/release-changelog-builder-action/issues/199#issuecomment-785190680
https://github.com/mikepenz/release-changelog-builder-action/issues/199#issuecomment-785191883

**Comment by kaermorchen** [comment]
@mikepenz I use action `checkout` (code above)

**Comment by mikepenz** [comment]
@kaermorchen does your repo have any tags?

**Comment by cmsj** [comment]
@kaermorchen do you have `fetch-depth: 0` in your checkout action? If not you've only checked out a single merge commit, which won't have any tags with it.

**Comment by mikepenz** [comment]
Thanks @cmsj. Totally forgot to mention that too. 

----

Usually the action is used for release builds, when the top is also the commit with the tag associated. (E.g. for the tag push trigger)

**Comment by mikepenz** [comment]
The problem should be resolved with the above answers. Please let me know if not, closing for the time being

**Comment by lgmorand** [comment]
Hello @mikepenz , I have the same issue in a workflow not using the tag trigger

Here is my yaml file

```
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 100
    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The repo has three tags, only one following the semver

Here is the error I get

Run mikepenz/release-changelog-builder-action@v1

```
📘 Reading input values
  /usr/bin/git rev-list --tags --skip=0 --max-count=1
  /usr/bin/git describe --abbrev=0 --tags 
  fatal: No names found, cannot describe anything.
  Error: The process '/usr/bin/git' failed with exit code 128
```

When I run the same commands manually, it finds one tag
```

E:\Repos\test>git rev-list --tags --skip=0 --max-count=1
abe0742fcbe9da4ed0c53a1440a325145fd49919

E:\Repos\test>git describe --abbrev=0 --tags
v1.0.0
```


What could be missing ?
