### ISSUE TITLE
Dynamic fromTag / toTag

### ISSUE THREAD

**Issue by hannesa2** [mikepenz/release-changelog-builder-action#229]
Thank you for this nice action !
I want to have a changelog form current tag to previous tag, do you have any idea to make this dynamic to prevent a commit in yml ?

eg `git log $(git describe --abbrev=0 --tags $(git describe --abbrev=0)^)...$(git describe --abbrev=0)`
same like `git log 2.16.0...2.15.3`

```
- name: "Complex Configuration"
  id: build_changelog
  uses: mikepenz/release-changelog-builder-action@{latest-release}
  with:
    fromTag: "2.15.3" <----  how to make this dynamic my previous tag, eg "git describe --abbrev=0 --tags $(git describe --abbrev=0)^"
    toTag: "2.16.0" <----  how to make this dynamic my current tag, eg "git describe --tags"
```
