### ISSUE TITLE
Multibranch changelog

### ISSUE THREAD

**Issue by OrKarstoft** [mikepenz/release-changelog-builder-action#256]
Hi!

I'm having a hard time figuring out how to get my changelog generated when I use a main-dev-feature setup.

We develop in feature branches and merges to dev branch. If everything works alright in dev we merge to main and release it. When the action runs on the main branch it says no changes in the changelog. Probably because it has no pull requests directly.

Are there any way to solve this?

**Comment by mikepenz** [comment]
Hi @OrKarstoft 

Not sure if this is a public project or private, allowing me to possibly check the logs. 

We use the action ourself with the same approach. 

PRs are getting merged into the dev branch, and releases are tagged on the main branch. (possibly with pre-releases on a QA branch) 

Are the PRs tagged with labels? something else which may could lead to them being dropped?

**Comment by OrKarstoft** [comment]
Thanks for fast reply!

Yeah, the projects are private. The one I'm testing on. But the logs looks like this.
![Screenshot 2021-04-07 at 09 43 34](https://user-images.githubusercontent.com/5990062/113829442-ccf53a80-9785-11eb-8f1e-42fb3993b6d6.png)

This project is just for testing the changelogs and make it work as we want.

I can see that it finds the PRs but doesn't use them. I've added a label to them all called `enhancement` and added the keyword to the configuration file as well. But since the logs says it can't find the configuration it probably why it doesn't work.

**Comment by mikepenz** [comment]
@OrKarstoft thanks for the screenshot. 

It looks like the configuration you specified is not found:

```
Configuration provided, but it couldn't be found. Fallback to Defaults.
```
This results in your `enhancement` label not being used for categorisation. 

The config is resolved in relation to the root of your project
```
configuration: ".github/config/releaseConfig.json"
```

Please also note that this file needs to exist for this (so please ensure it get's checked out)

**Comment by OrKarstoft** [comment]
I'm just using the simple config as you've written in the documentation and changed the path.
```
name: 'CI'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: ".github/config/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

And also the configuration file is in the right place.
![Screenshot 2021-04-07 at 10 05 56](https://user-images.githubusercontent.com/5990062/113832383-ddf37b00-9788-11eb-9831-9c806ad18be2.png)

**Comment by mikepenz** [comment]
@OrKarstoft the most basic example in the README does not use a configuration (which will not require a checkout) 

The way github actions functions, if you do not call the `checkout` step, the action will not have the files available, in this case including the configuration. 

Please add the `checkout` so the config will be available :) https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L99-L108

**Comment by OrKarstoft** [comment]
Alright. Adding the `checkout` seemed to do a lot of good! It found my configuration and created the changelog correctly. 👍 

Awesome, I'll work with this. Thanks a lot @mikepenz!

**Comment by mikepenz** [comment]
Thank you so much! 

Also added this note additionally in the configuration section of the README, hopefully making it more clear. 

Please feel free to open a PR with further clarifications to the README, if something could be phrased better.

**Comment by OrKarstoft** [comment]
Hi @mikepenz 

With this configuration I only have one PR in the changelog and it's the PR from `dev` to `master`. Are there any way I can add to the configuration to use all the PRs that makes the dev? I can't seem to figure out how you do. 🤔 

Of course it works when I make the tag from the `dev` branch but is that the way?

**Comment by mikepenz** [comment]
@OrKarstoft which specific configuration do you use currently?

If something strange is happening and you wanna quickly debug and retest configurations. you can run the tests locally on your machine and give it the configuration you wanna try :) should give an easier time to quickly iterate on things

**Comment by OrKarstoft** [comment]
Thanks for getting back to me.

```json
{
  "categories": [
    {
      "title": "## 🚀 Features and enhancements",
      "labels": [
        "feature",
        "enhancement"
      ]
    },
    {
      "title": "## 🐛 Fixes",
      "labels": [
        "fix"
      ]
    },
    {
      "title": "## 🧪 Tests",
      "labels": [
        "test"
      ]
    },
    {
      "title": "## 📖 Documentation",
      "labels": [
        "documentation"
      ]
    }
  ],
  "max_pull_requests": 1000,
  "max_back_track_time_days": 1000
}
```

```yaml
name: 'CI'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1.8.3
        with:
          configuration: ".github/changelog/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Those are my configurations.  

I squash and merge from my feature branches to `dev` and squash and merge from `dev` to `master`. When everything is in main I create a tag and I only get the PR from `dev` to `master`. I guess it makes sense as there really only is one but I'd like it to show all them from feature branches to `dev` instead. Tried a bunch of stuff but I can't really get my head around how to do it other than release from `dev`.
