### ISSUE TITLE
Unable to retrieve previous tag

### ISSUE THREAD

**Issue by elendil-software** [mikepenz/release-changelog-builder-action#260]
Hi,

I try to use release-changelog-builder-action but I get this error : 

> Error: 💥 Unable to retrieve previous tag given 0.1.0

![image](https://user-images.githubusercontent.com/11425952/114144567-c269ab00-9915-11eb-8c9c-01348d3a2a64.png)

my workflow file is :

```
name: Test Build Changelog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v1.7.1
      with:
        failOnError: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Print Changelog"
      run: echo ${{steps.build_changelog.outputs.changelog}}
```
And currently my repository looks like : 

![image](https://user-images.githubusercontent.com/11425952/114144853-11174500-9916-11eb-947e-f12eca0e0b99.png)

Did I missed something ?
