### ISSUE TITLE
Add and push the changelog file to repository 

### ISSUE THREAD

**Issue by jossefaz** [mikepenz/release-changelog-builder-action#360]
Hi

I try to add, commit and push the output change log file to the repository. 

```
name: build-version-workflow

on: push 
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 1
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with: 
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create local changes
        run: |
          git add ${{steps.build_changelog.outputs.changelog}}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Change Log Created / Updated"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
```

But the ouptut file does not seems to be a path...and when I try to add it (btw I am using this github actions for push : https://github.com/marketplace/actions/github-push) it fails with this error : 

```
Run git add - no changes
fatal: pathspec '-' did not match any files
```

I thought it was related to the push actions but I noticed that the `git add` is actually pointing to empty path...
I am not sur on what I am doing wrong here. Did I reference the output changelog file correctly ?

Any help on that would be more than welcome !
