### ISSUE TITLE
empty template being output as changelog despite changes being present

### ISSUE THREAD

**Issue by kian2attari** [mikepenz/release-changelog-builder-action#390]
Despite the fact that the action is able to resolve the tag and determine there are changes between them, it outputs the default "no changes" as the changelog.

![image](https://user-images.githubusercontent.com/24510265/125872487-662cb1dc-c4c0-4663-81c3-80a61fe9353c.png)

My example config is as follows:

```
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v2.1.0
        with:
          owner: ${{ github.repository_owner }}
          configuration: changelog-config.json
          repo: test-repo
          fromTag: v.0.15.0
          toTag:  v.0.19.0
          failOnError: true
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

I've tried outputting to a file as well, same result. I've also tried with `commitMode` set to true and false with no success. Removing the `toTag` and `fromTag` makes no difference as well. It always outputs `- no changes` as the changelog
