### ISSUE TITLE
Bypass shallow clone issue?

### ISSUE THREAD

**Issue by guilhermeblanco** [mikepenz/release-changelog-builder-action#433]
I'm working to add support changelog generation using this project (and moving away from the old create release support `marvinpinto/action-automatic-releases`) in conjunction with `softprops/action-gh-release`.

Here is the smallest sample I could narrow down:

```yaml
  name: build-artifact
  on:
    push:
      branches:
        - main

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          id: checkout_repository
          uses: actions/checkout@v2

        - name: Build changelog
          id: build_changelog
          uses: mikepenz/release-changelog-builder-action@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The idea is to generate a changelog from the last released tag against all merged PRs (or direct commits to the main branch).

Unfortunately, this is the issue I experience on Github actions:

```
Run mikepenz/release-changelog-builder-action@v2
  with:
    ignorePreReleases: true
    failOnError: false
    commitMode: false
  env:
    GITHUB_TOKEN: ***

📘 Reading input values
  /usr/bin/git rev-list --tags --skip=0 --max-count=1
  /usr/bin/git describe --abbrev=0 --tags 
  fatal: No names found, cannot describe anything.
  Error: The process '/usr/bin/git' failed with exit code 128
``` 

My understanding is that because actions/checkout makes a shallow clone, there are no tags fetched.
Nowhere in the documentation there is any mention about this issue, which hints me that either I am doing something wildly wrong, or there is a missing step somewhere (not represented in the full example).

I'm thinking something like this:

```yaml
jobs:
    steps:
      - name: Checkout repository
        id: checkout_repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
``` 

Or maybe like this (sometimes the previous one doesn't cut it):

```yaml
jobs:
    steps:
      - name: Checkout repository
        id: checkout_repository
        uses: actions/checkout@v2

     - name: Unshallow repository checkout
       run: git fetch --prune --unshallow
``` 

Unfortunately, depending of the size of the repository, this may be impossible to do. 
Any feedback would be appreciated.
