### ISSUE TITLE
Error: Unable to resolve action `actions/create-release@v3`, unable to find version `v3`

### ISSUE THREAD

**Issue by johnico** [mikepenz/release-changelog-builder-action#790]
i got 

Error: Unable to resolve action `actions/create-release@v3`, unable to find version `v3`

while running the example on the docs

thanks

**Comment by mikepenz** [comment]
Thanks for noting this. this action is discontinued by GitHub (was only noted by reference)

Personally I like to use: https://github.com/softprops/action-gh-release these days

**Comment by johnico** [comment]
@mikepenz thanks a lot 
Can you have  a full example of it ? I tried and I don't mange to print the steps from your actions .it alwas create the releaaee with no chabges 
And for sure there was

**Comment by johnico** [comment]
@mikepenz   thanks. 
```
name: 'CI'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ steps.github_release.outputs.changelog }}
          GITHUB_TEST: ${{ toJson(steps)}}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_TEST"
```


teps.github_release.outputs.changelog. is always. "no changes"


the steps output is : 

```
  ℹ️ Comparing XX- 'v0.0.2-10...v0.0.2-11'
  ℹ️ Found 13 commits from the GitHub API forXX
  ℹ️ Fetching PRs between dates 2022-06-20T19:41:30.000Z to 2022-06-20T20:02:02.000Z for XX
  ℹ️ Retrieved 14 merged PRs forXX
  ℹ️ Retrieved 13 release commits for  XX

📦 Build changelog
  ℹ️ Sorted all pull requests ascending: [object Object]
  ℹ️ Used 0 transformers to adjust message
  ✒️ Wrote messages for 1 pull requests
  ℹ️ Ordered all pull requests into 3 categories
  ✒️ Wrote 0 categorized pull requests down
  
  ✒️ Wrote 1 non categorized pull requests down
  
  ✒️ Wrote 0 ignored pull requests down
  ℹ️ Filled template
```
