### ISSUE TITLE
Repeatedly getting `Only one tag found for the given repository. Usually this is the case for the initial release.`

### ISSUE THREAD

**Issue by sebastianwachter** [mikepenz/release-changelog-builder-action#796]
The GitHub action repeatedly generates a "no changes" changelog even when there were labeled pull requests merged in between the versions. I think the problem is found somewhere in the tag resolution for this repository.

To produce the following output I did the following:

- On branch `staging` with tag `v0.0.8`
- Create a new branch with changes, create a PR onto `staging` and add a label `fix` to this PR
- Merge that PR and update my local `staging` branch with `git pull origin staging`
- Increase the version with `npm version patch` -> `v0.0.9`
- Push the tag with `git push origin staging --follow-tags`

`createReleaseChangelog.yml`:

```yml
name: Create Release and Create Changelog
on: [push]

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: changelog-configuration.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{steps.github_release.outputs.changelog}}
```

`changelog-configuration.json`:

```json
{
    "categories": [
      {
        "title": "## 🚀 Features",
        "labels": ["feature"]
      },
      {
        "title": "## 🐛 Fixes",
        "labels": ["fix"]
      },
      {
        "title": "## 🧪 Tests",
        "labels": ["test"]
      },
      {
        "title": "## ✨ Magic",
        "labels": ["magic"]
      }
    ],
    "ignore_labels": [
      "ignore"
    ],
    "sort": {
      "order": "ASC",
      "on_property": "mergedAt"
    },
    "template": "${{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n${{UNCATEGORIZED}}\n</details>",
    "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}",
    "empty_template": "- no changes",
    "label_extractor": [
      {
        "pattern": "(.) (.+)",
        "target": "$1",
        "flags": "gu"
      },
      {
        "pattern": "\\[Issue\\]",
        "on_property": "title",
        "method": "match"
      }
    ],
    "duplicate_filter": {
      "pattern": "\\[ABC-....\\]",
      "on_property": "title",
      "method": "match"
    },
    "transformers": [
      {
        "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
        "target": "- $4\n  - $6"
      }
    ],
    "max_tags_to_fetch": 1000,
    "max_pull_requests": 1000,
    "max_back_track_time_days": 365,
    "exclude_merge_branches": [
      "Owner/qa"
    ],
    "tag_resolver": {
      "method": "semver",
      "filter": {
        "pattern": "api-(.+)",
        "flags": "gu"
      }
    },
    "base_branches": [
      "dev"
    ]
}
```

Log:

```
Run mikepenz/release-changelog-builder-action@v3
  with:
    configuration: changelog-configuration.json
    includeOpen: false
    ignorePreReleases: false
    failOnError: false
    fetchReviewers: false
    commitMode: false
  env:
    GITHUB_TOKEN: ***
  
📘 Reading input values
  ℹ️ Configuration successfully loaded.
  
  
🔖 Resolve tags
  ℹ️ Found 1[2](https://github.com/<private>/runs/7088282055?check_suite_focus=true#step:3:2) (fetching max: 1000) tags from the GitHub API for <private>
  🔖 Resolved current tag (v0.0.9) from the 'github.context.ref'
  ℹ️ Only one tag found for the given repository. Usually this is the case for the initial release.
  /usr/bin/git rev-list --max-parents=0 HEAD
  5c9e17757804d8f06ec45e6fa45[3](https://github.com/<private>/runs/7088282055?check_suite_focus=true#step:3:3)071baddfdf0f
  🔖 Resolved initial commit (5c9e1775780[4](https://github.com/<private>/runs/7088282055?check_suite_focus=true#step:3:4)d8f06ec4[5](https://github.com/<private>/runs/7088282055?check_suite_focus=true#step:3:5)e[6](https://github.com/<private>/runs/7088282055?check_suite_focus=true#step:3:6)fa4530[7](https://github.com/<private>/runs/7088282055?check_suite_focus=true#step:3:7)1baddfdf0f) from 'git rev-list --max-parents=0 HEAD'
  🔖 Resolved previous tag (5c9e17757[8](https://github.com/<private>/runs/7088282055?check_suite_focus=true#step:3:8)04d8f06ec45e6fa453071baddfdf0f) from the tags git API
  
  
🚀 Load pull requests
  ℹ️ Comparing <private> - '5c[9](https://github.com/<private>/runs/7088282055?check_suite_focus=true#step:3:9)e17757804d8f06ec45e6fa453071baddfdf0f...v0.0.9'
  ℹ️ Found 1859 commits from the GitHub API for <private>
  ℹ️ Fetching PRs between dates 2021-[11](https://github.com/<private>/runs/7088282055?check_suite_focus=true#step:3:11)-04T09:36:46.000Z to 2022-06-28T08:00:54.000Z for <private>
  ℹ️ Retrieved 374 merged PRs for <private>
  ℹ️ Retrieved [18](https://github.com/<private>/runs/7088282055?check_suite_focus=true#step:3:19)59 release commits for <private>
  
Warning: ⚠️ No pull requests found
```

Do you have any leads on what might be causing this?
