### ISSUE TITLE
build a change log only between release that are not prerelease? is it optional ? 

### ISSUE THREAD

**Issue by johnico** [mikepenz/release-changelog-builder-action#800]
I have  a dev branch 
once i want to deploy the dev i have created a new git tag lets say 1.0.0-rc.0 
and each new feature i will created another tag - 1.0.0-rc.1 
those will a "pre-release" version

now i would like to create a new release from main and i created a 1.0.1 tag 
but the changelog will print only the diffrence betwen 1.0.1 to 1.0.0-rc.1 and will not include the 1.0.0-rc.0 

how can i fix it ? is it possible 
can someone share an exmaple ? 
so in case i m on main branch i would like to compare only main tags 

thanks for a amzaing github action btw

**Comment by mikepenz** [comment]
Yes this is possible. You can configure it by defining the `ignorePreReleases` configuration. 

```yml
- uses: mikepenz/release-changelog-builder-action@v3
   with:
      ignorePreReleases: true
```

Find more information in the README
