### ISSUE TITLE
No Information in release

### ISSUE THREAD

**Issue by buckmaxwell** [mikepenz/release-changelog-builder-action#855]
Hi - thrilled to use this. Seems like it should fit our use case perfectly. Though the pipeline runs - and indeed creates a tag, there is no information in the release. Any idea what I am doing wrong? I will include my github actions pipleline code. Thanks again for this project!

<img width="639" alt="Screen Shot 2022-08-09 at 10 25 14 AM" src="https://user-images.githubusercontent.com/6210452/183674512-c13d7433-59e3-402f-84d3-c90d4cc7995e.png">

<img width="1255" alt="Screen Shot 2022-08-09 at 10 26 08 AM" src="https://user-images.githubusercontent.com/6210452/183674716-f5616cdd-4316-4696-b001-091009d9eab2.png">

```yaml
name: 'Generate Changelog'

on:
  push:
    tags:
      - 'w*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: "changelog-builder.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}
```

**Comment by mikepenz** [comment]
Thank you for the report @buckmaxwell 

the log indicates that there were 51 pull requests matched for this release. 
But none of these were categorized. 

The categorization works based on PR `labels`. 

By default it looks for the following labels: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L80-L93

Make sure the PRs have such labels assigned, and then they will be categorized. 

In case you want to adjust the `template` to also include non categorized PRs. (by default they are not included: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L77) - You may want to use a template like:

```
"template": "${{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n${{UNCATEGORIZED}}\n</details>",
```
 (as part of a full example: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/configs/configuration_complex.json)

**Comment by buckmaxwell** [comment]
Thank you so much for your quick reply. I tried changing to a setup that looks like this but I am still having no information included in the release log.

Maybe worth mentioning - my tag is on a different branch from master.


```yml
name: 'Generate Changelog'

on:
  push:
    tags:
      - 'w*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: "changelog-builder.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}
```

The changelog-builder.json looks like this,

```json
{
  "categories": [
    {
      "title": "## 🚀 Features",
      "labels": [
        "feature"
      ]
    },
    {
      "title": "## 🐛 Fixes",
      "labels": [
        "fix"
      ]
    },
    {
      "title": "## 🧪 Tests",
      "labels": [
        "test"
      ]
    }
  ],
  "sort": "ASC",
  "template": "${{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n${{UNCATEGORIZED}}\n</details>",
  "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}",
  "empty_template": "- no changes",
  "transformers": [
    {
      "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
      "target": "- $4\n  - $6"
    }
  ],
  "max_tags_to_fetch": 200,
  "max_pull_requests": 20,
  "max_back_track_time_days": 90
}
```
