### ISSUE TITLE
No category label other than the default ones are working in configuration input

### ISSUE THREAD

**Issue by KausarNaqvi** [mikepenz/release-changelog-builder-action#882]
input option "configurationJson" has an option for categories, in which we can specify the labels and there corresponding titles to appear in the change log.

![image](https://user-images.githubusercontent.com/106592880/187087357-fd579b62-8940-40f7-9839-69acc30077af.png)

I am unable to pass 

-  "feat" in addition to "feature" or 
-  "bug" in addition to "fix". 

If I pass that, the pull requests with label "feat", "bug" do not appear in the changeLog. They are taken as the uncategorized pull requests.

**Comment by KausarNaqvi** [comment]
@mikepenz

**Comment by mikepenz** [comment]
@KausarNaqvi as you can see in your log above the configuration was provided, but it couldn't be parsed. Which results in it falling back to the default:
<img width="453" alt="Screen Shot 2022-08-28 at 21 22 26" src="https://user-images.githubusercontent.com/1476232/187090978-97b07e49-f31e-420f-9c0d-f826e806be9d.png">

In your config it looks you have an invalid json. The last item in an array has a `,` after it. which is looks to be the issue. 

<img width="224" alt="Screen Shot 2022-08-28 at 21 23 07" src="https://user-images.githubusercontent.com/1476232/187091009-a802c11e-948a-4ce0-a863-41fe68418433.png">
 
Remove the `,` and make sure the full json is a valid json. (you can see in the log if it was able to parse it

**Comment by KausarNaqvi** [comment]
@mikepenz will apply the suggested changes! Thanks.

**Comment by mikepenz** [comment]
@KausarNaqvi were you able to resolve the problem by removing the `,`?

**Comment by KausarNaqvi** [comment]
@mikepenz  I used the other approach
- made a configuration.json file and pass it to the configuration input instead of using configurationJson.

That worked like a charm!

**Comment by KausarNaqvi** [comment]
@mikepenz but yes I think there was some issue with the syntax. When I made a separate file, I might had fixed the syntax issue because the code editor used to show the errors and it worked fine.

**Comment by Ojasv-Singh-Zeotap** [comment]
I am facing the same issue. I am getting changelog as empty even when in logs i can see `Wrote 95 non categorized pull requests down`

using a configuration.json file as follows 
```
{
  "categories": [
    {
      "title": "## 🚀 Features",
      "labels": []
    },
    {
      "title": "## 🐛 Fixes",
      "labels": [
        "fix"
      ]
    },
    {
      "title": "## 🧪 Tests",
      "labels": [
        "test"
      ]
    }
  ],
  "ignore_labels": [
    "ignore"
  ],
  "sort": {
    "order": "ASC",
    "on_property": "mergedAt"
  },
  "template": "${{CHANGELOG}}\n\n{{RELEASE_DIFF}}\n\n<details>\n<summary>Uncategorized</summary>\n\n${{UNCATEGORIZED}}\n</details>",
  "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}",
  "empty_template": "- no changes",
  "base_branches": [
    "master"
  ]
}
```
I dont have lables on my commits and want to have those commits in uncategorized category. 

Following are the debug logs of workflow
<img width="804" alt="image" src="https://user-images.githubusercontent.com/77407526/188655959-8ad774f2-a194-493d-ba45-720fccc988f1.png">

Below is my workflow.yml file
```
create-changelog:
    needs: [ create-tag, create-release-version ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout to master branch
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: 'test'
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: "configuration.json"
          ignorePreReleases: "false"
          toTag: v${{needs.create-release-version.outputs.RELEASE_VERSION}}
      - name: debug
        run: |
          echo "${{toJson(steps.changelog.outputs)}}"
          echo "${{steps.changelog.outputs}}"
          echo "changelog: ${{steps.changelog.outputs.changelog}}"
          echo "changelog1: ${{steps.changelog.outputs.CHANGELOG}}"
          echo "changes: ${{steps.changelog.outputs.changes}}"
          echo "changes_op1: ${{steps.changelog.outputs.CHANGE_LOG_VAR}}"
          echo "changes_op2: ${{steps.changelog.outputs.CHANGE_LOG_VAR1}}"
          echo "uncat: ${{steps.changelog.outputs.UNCAT}}"
```

The json output of `steps.changelog.outputs` is as follows
```
{
  failed: false,
  owner: zeotap,
  repo: dazz-data-manager,
  toTag: v1.2.3,
  fromTag: v1.0.0,
  pull_requests: 836,858,861,869,868,870,875,893,891,898,900,903,906,907,910,911,912,914,951,950,958,961,962,963,966,967,968,969,970,973,944,975,976,977,972,979,978,980,981,943,965,983,971,987,989,990,992,993,996,997,994,999,1001,1003,1004,1005,1006,1007,1008,1010,1011,991,988,974,1012,1014,1015,1019,1021,1022,1025,1026,1030,1034,1037,1038,1043,1039,1058,1066,1069,1067,1073,1096,1097,1103,1083,1108,1111,1112,1105,1126,1127,1128,1129,
  changed_files: 645,
  additions: 2[31](https://github.com/zeotap/dazz-data-manager/runs/8208615070?check_suite_focus=true#step:4:32)25,
  deletions: 88[32](https://github.com/zeotap/dazz-data-manager/runs/8208615070?check_suite_focus=true#step:4:33),
  changes: 31957,
  commits: 560,
  categorized_prs: 0,
  uncategorized_prs: 95,
  changelog: 
}
Object
changelog: 
changelog1: 
changes: 31957
changes_op1: 
changes_op2: 
uncat:
```

@KausarNaqvi @mikepenz Would appreciate any help. Thankyou
