### ISSUE TITLE
PRs not showing up in release notes or in CHANGELOG

### ISSUE THREAD

**Issue by hussainaloum** [mikepenz/release-changelog-builder-action#911]
Hello

I'm trying to update my release notes/ CHANGLOG after I issue a release. I'm using the following in my github actions workflow

```
    job2:
      if: ${{ github.event_name == 'release' }}
      runs-on: ubuntu-20.04
      name: Build firmware on 'release'
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0                              # required to fetch all history for all branches and tags

        - name: Give GitHub Actions access to submodules
          uses: webfactory/ssh-agent@v0.5.4
          with:
            ssh-private-key: |
              ${{ secrets.X }}
              ${{ secrets.X }}

        - name: Update lists
          run: sudo apt-get update

        - name: Build Changelog
          id: github_release
          uses: mikepenz/release-changelog-builder-action@v3
          with:
            configuration: "configuration.json"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create Release
          uses: mikepenz/action-gh-release@v1 #softprops/action-gh-release
          with:
            body: ${{steps.github_release.outputs.changelog}}
```

and my configuration.json file is below

```
{
    "categories": [
      {
        "title": "## 🚀 Features",
        "labels": ["feature"],
        "empty_content": "- no matching PRs"
      },
      {
        "title": "## 🐛 Fixes",
        "labels": ["fix"],
        "empty_content": "- no matching PRs"
      },
      {
        "title": "## 🧪 Tests",
        "labels": ["test"],
        "empty_content": "- no matching PRs"
      },
      {
        "title": "## 🧪 Tests and some 🪄 Magic",
        "labels": ["test", "magic"],
        "exclude_labels": ["no-magic"],
        "exhaustive": true,
        "empty_content": "- no matching PRs"
      }
    ],
    "ignore_labels": [
      "ignore"
    ],
    "sort": {
      "order": "ASC",
      "on_property": "mergedAt"
    },
    "template": "${{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n${{UNCATEGORIZED}}\n</details>",
    "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}",
    "empty_template": "- no changes",
    "label_extractor": [
      {
        "pattern": "(.) (.+)",
        "target": "$1",
        "flags": "gu"
      },
      {
        "pattern": "\\[Issue\\]",
        "on_property": "title",
        "method": "match"
      }
    ],
    "duplicate_filter": {
      "pattern": "\\[ABC-....\\]",
      "on_property": "title",
      "method": "match"
    },
    "transformers": [
      {
        "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
        "target": "- $4\n  - $6"
      }
    ],
    "max_tags_to_fetch": 200,
    "max_pull_requests": 200,
    "max_back_track_time_days": 365,
    "exclude_merge_branches": [
      "Owner/qa"
    ],
    "tag_resolver": {
      "method": "semver",
      "filter": {
        "pattern": "api-(.+)",
        "flags": "gu"
      }
    },
    "base_branches": [
      "dev"
    ]
}
```
I made a PR and attached the label "feature" and then I made a release, however I don't see the PR show up in the feature section in my release notes. 
<img width="1259" alt="Screen Shot 2022-10-03 at 11 15 46 AM" src="https://user-images.githubusercontent.com/36559536/193627562-ab589f10-d039-4eb8-b7d2-e5f6db81ea88.png">

The only thing I see is the following
<img width="919" alt="Screen Shot 2022-10-03 at 11 12 47 AM" src="https://user-images.githubusercontent.com/36559536/193626988-965096c2-1d03-4c70-8810-60f16ac0b82e.png">

Is there anything here I'm doing wrong?
