### ISSUE TITLE
Changelog is empty

### ISSUE THREAD

**Issue by Ian1971** [mikepenz/release-changelog-builder-action#923]
I am always getting an empty change log, though the logs do seem to indicate it found something.

```
    - name: Build Changelog
      id: github_release
      uses: xxx/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
    - run: |
        echo "changelog: ${{steps.github_release.outputs.changelog}}"    
```

```
 🚀 Load pull requests
  ℹ️ Comparing xxx/yyy - 'v1.0.77...v1.0.79'
  ℹ️ Found 2 commits from the GitHub API for xxx/yyy
  ℹ️ Fetching PRs between dates 2022-10-14T13:07:19.000Z to 2022-10-14T13:17:05.000Z for xxx/yyy
  ℹ️ Retrieved 42 merged PRs for xxx/yyy
  ℹ️ Retrieved 2 release commits for xxx/yyy
  
📦 Build changelog
  ℹ️ Sorted all pull requests ascending: {"order":"ASC","on_property":"mergedAt"}
  ℹ️ Used 0 transformers to adjust message
  ✒️ Wrote messages for 1 pull requests
  ℹ️ Ordered all pull requests into 3 categories
  ✒️ Wrote 0 categorized pull requests down
  
  ✒️ Wrote 1 non categorized pull requests down
  
  ✒️ Wrote 0 ignored pull requests down
  ℹ️ Filled template
```

Any ideas what I might be doing wrong?
