### ISSUE TITLE
Can I get some help to get this working please?

### ISSUE THREAD

**Issue by TheLastDarkthorne** [mikepenz/release-changelog-builder-action#939]
[EDITED: I made a rookie mistake lol it is fixed, but it is still not working :( ]
Hello! I'm not a github pro and I have been trying to make this work with a repo I contribute for hours but it is not working. I wanted to test first so all the things here are just testing things. It detects some PRs but then it issues a warning that it no PRs were found? I don't understand why. And in the release it only puts 'no changes'. I labelled the PRs correctly or at least I think I did (I created a few test PRs you can see in the repo if you want)

![image](https://user-images.githubusercontent.com/36555422/197840074-dbde7133-8919-4c5c-b479-05bc3f595616.png)

Here's the action

```yaml
name: 'CI'
on:
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0
        with:
          #ref: in-client-svof
          ref: release-experiments
          fetch-depth: 0
      
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3.4.0
        with:
          configuration: "release-changelog-configuration.json"
          ignorePreReleases: "false"
          toTag: "51"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

And the configuration:

```json
{
    "categories": [
        {
            "title": "## 🚀 Enhancements",
            "labels": ["enhancement"]
        },
        {
            "title": "## 🐛 Fixes",
            "labels": ["bug"]
        },
        {
            "title": "## 🧪 Tests",
            "labels": ["test"]
        }
    ],
    "sort": "ASC",
    "template": "${{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n${{UNCATEGORIZED}}\n</details>",
    "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}",
    "empty_template": "- no changes",
    "transformers": [
        {
            "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
            "target": "- $4\n  - $6"
        }
    ],
    "max_pull_requests": 100,
    "max_back_track_time_days": 365,
    "base_branches": [
      "release-experiments"
    ]
}
```

And the full log in case you need it

[log.txt](https://github.com/mikepenz/release-changelog-builder-action/files/9862493/log.txt)

Thank you very much!!
