### ISSUE TITLE
bug: crash when use a custom config

### ISSUE THREAD

**Issue by eXponenta** [mikepenz/release-changelog-builder-action#963]
pipeline:
```
name: Up to new new version
on:
  push:
    tags:
      - v*
env:
  REF_BRANCH: dev
  TARGET_BRACH: main
  VERSION_COMMAND: release:prerelease

jobs:
  merge-dev-to-main:
    name: Sync main with dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.REF_BRANCH }}
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge dev to main
      run: |
          git fetch --unshallow
          git checkout $TARGET_BRACH
          git pull
          git merge $REF_BRANCH
    - name: Install node
      uses: actions/setup-node@main
      with:
        node-version: 17.9.0
    - name: Install yarn
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build dev version
      uses: borales/actions-yarn@v4
      with:
        cmd: release-dev
    - name: Build s3 version
      uses: borales/actions-yarn@v4
      with:
        cmd: release
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - name: Commit build
      run: |
        git add --all
        git commit -m "Build:v${{ steps.package-version.outputs.current-version}}"
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@develop
      with:
        configuration: ".github/changelog.config.json"
        commitMode: true
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the changelog
      run: |
            echo ${{ steps.build_changelog.outputs.changelog }}
            cat >> CHANGELOG.MD << EOF
            ${{ steps.build_changelog.outputs.changelog }}
            EOF
    - name: Push result
      run: |
          git add --all
          git commit -m "Changelog"
          git push
          git push --tags

```
config:
```
{
    "categories": [
      {
        "title": "## 🚀 Features",
        "labels": ["feature", "feat", "FEAT"]
      },
      {
        "title": "## 🐛 Fixes",
        "labels": ["fix", "FIX"]
      },
      {
        "title": "## 🧪 Tests",
        "labels": ["test"]
      },
      {
        "title": "## 🧪 Tests and some 🪄 Magic",
        "labels": ["test", "magic"],
        "exclude_labels": ["no-magic"],
        "exhaustive": true,
        "empty_content": "- no matching PRs"
      },
	  {
		"title": ["improvements", "enhancement"],
		"label": "🔨 Improvements"
	  }
    ],
    "ignore_labels": [
      "ignore", "other"
    ],
    "sort": {
      "order": "ASC",
      "on_property": "mergedAt"
    },
    "template": "${{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n${{UNCATEGORIZED}}\n</details>",
    "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}"
}

```
result:
![image](https://user-images.githubusercontent.com/12572222/204765339-29eeca8e-a493-4072-8b22-ca2b977dc10e.png)
