### ISSUE TITLE
[Question] build step is not running

### ISSUE THREAD

**Issue by codebydant** [mikepenz/release-changelog-builder-action#981]
Hi @mikepenz,

Thanks for this wonderful tool.

I would like to ask you if you know why might this happen. I am trying to build the changelog between 2 tags:

```yml
fromTag: "api_fronten/v2.1.36"
toTag: "api_fronten/v2.1.37"
```

I have these tags
![Screenshot from 2022-12-16 06-00-53](https://user-images.githubusercontent.com/115469901/208084351-10e1f29d-81a7-4e39-8a75-9c71cc2a4872.png)

But, after running the workflow, the build step is not running because I don't have merged PR?

## workflow

```yml
- name: "Build Changelog"
  id: build_changelog
  uses: mikepenz/release-changelog-builder-action@v3.5.0
  with:
    fromTag: "api_fronten/v2.1.36"
    toTag: "api_fronten/v2.1.37"
    configurationJson: |
      {
        "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
        "categories": [
          {
              "title": "## 💬 Other",
              "labels": ["other"]
          },
          {
              "title": "## 📦 Dependencies",
              "labels": ["dependencies"]
          }
        ]
      }
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## result
![Screenshot from 2022-12-16 06-53-48](https://user-images.githubusercontent.com/115469901/208092752-0d494f24-b458-4c8c-84ba-05985fb79e3f.png)

Do you know what I might be doing wrong?
