### ISSUE TITLE
New feature category rules might not be working

### ISSUE THREAD

**Issue by codebydant** [mikepenz/release-changelog-builder-action#999]
Hi @mikepenz,

Thanks for this wonderful tool :rocket: 

I have been trying to set the new feature **categories rules** to create the "Unreleased" section in the changelog and it works. I mean, I am getting the open PRs in a new section but without the categorization. I have used the example in the docs to configure this, but I am not sure I am missing something.

![Screenshot from 2023-01-06 06-22-36](https://user-images.githubusercontent.com/115469901/211002939-d3a93057-b918-4064-a5d1-4ac1e65b07fe.png)

## configrc
```yml
configurationJson: |
      {
        "categories": [
          {
            "title": "## 🚀 Features",
            "labels": [
              "feat(${{ inputs.scope }})"
            ],
            "rules": [
              {
                "pattern": "open",
                "on_property": "status",
                "flags": "gu"
              }
            ]
          },
          {
            "title": "## 🐛 Fixes",
            "labels": [
              "fix(${{ inputs.scope }})"
            ],
            "rules": [
              {
                "pattern": "open",
                "on_property": "status",
                "flags": "gu"
              }
            ]
          },
          {
            "title": "## 🧪 Tests",
            "labels": [
              "test(${{ inputs.scope }})"
            ],
            "exhaustive": true,
            "rules": [
              {
                "pattern": "open",
                "on_property": "status",
                "flags": "gu"
              }
            ]
          }
        ],              
        "sort": {
          "order": "ASC",
          "on_property": "mergedAt"
        },
        "template": "All notable changes to this project will be documented in this file.\n\n## Changes #{{RELEASE_DIFF}}\n\n#{{CHANGELOG}}## 💬 Other\n\n#{{UNCATEGORIZED}}\n## 📖 Unreleased\n#{{OPEN}}",
        "pr_template": "- ##{{NUMBER}} #{{TITLE}} @#{{AUTHOR}}",
        "label_extractor": [
          {
            "pattern": ".*(feat\\(${{ inputs.scope }}\\)).*",
            "target": "$1",
            "on_property": "title"
          },
          {
            "pattern": ".*(fix\\(${{ inputs.scope }}\\)).*",
            "target": "$1",
            "on_property": "title"
          },
          {
            "pattern": ".*(test\\(${{ inputs.scope }}\\)).*",
            "target": "$1",
            "on_property": "title"
          }
        ]
      }
```

Related to #725
